version: '3.8'

services:
  djangoserver:
    container_name: Account_task
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"






